### ISSUE TITLE
Agreguen a Flash

### ISSUE THREAD

**Issue by JGonzalesCastillo** [arcadio1894/comics#5]
### Flash es uno de los principales **_héroes de DC_**.
`npm install `
`php artisan migrate:fresh --seed`

**Comment by arcadio1894** [comment]
Es cierto, pero por ahora el juego no contempla a Flash. Más adelante si lo agregaremos.

**Comment by JGonzalesCastillo** [comment]
A ya, gracias por tenerlo en cuenta.

**Comment by arcadio1894** [comment]
Vamos a agregar a Flash

**Comment by JGonzalesCastillo** [comment]
Ok. Estaré esperando el cambio

**Comment by arcadio1894** [comment]
Flash fue agregado a héroes 26ffb23
